FROM python:3.11-slim-bookworm

WORKDIR /app

RUN pip install poetry

COPY frontend/poetry.lock ./

COPY frontend/pyproject.toml ./

RUN poetry install

COPY frontend/frontend frontend/

COPY frontend/frontend/Streamlit_data Streamlit_data

CMD poetry run streamlit run --server.port 8080 frontend/Streamlit_GUI.py --server.address 0.0.0.0
