version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      - app
    
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge