FROM python:3.11-slim-bookworm

WORKDIR /app

RUN pip install poetry

COPY backend/poetry.lock backend/pyproject.toml ./

RUN poetry install

COPY backend/backend/images_fastapi images_fastapi/

COPY backend/backend/model_parameters model_parameters/

COPY backend/backend/FastAPI.py .

CMD ["poetry","run","uvicorn", "FastAPI:app", "--host", "0.0.0.0", "--port", "8000","--reload" ]

