version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile_frontend
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend/frontend/Dataset-trafo
        target: /app/Dataset-trafo
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - 8000:8000
  nginx:
      container_name: nginx
      restart: unless-stopped
      image: nginx
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
        - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem


