version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      - app
    volumes:
      - type: bind
        source: ./frontend/frontend/Dataset-trafo
        target: /app/Dataset-trafo
    
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - 8000:8000
    networks:
      - app
networks:
  app:
    driver: bridge